version: "3.8"

services:

  mongodb_docencia:
    image: mongo:7
    container_name: mongodb_docencia
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo_express_docencia
    restart: always
    ports:
      - "8091:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb_docencia:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb_docencia

volumes:
  mongo_data:
